"""add_client_case_deleted_at

Revision ID: 140ca9079e15
Revises: 72b8ab7e41ac
Create Date: 2026-06-13 10:45:36.387557

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140ca9079e15'
down_revision: Union[str, Sequence[str], None] = '72b8ab7e41ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_case', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_client_case_deleted_at'), 'client_case', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_case_deleted_at'), table_name='client_case')
    op.drop_column('client_case', 'deleted_at')
    # ### end Alembic commands ###
