"""add_saved_view

Revision ID: 72b8ab7e41ac
Revises: d16404291a1d
Create Date: 2026-06-13 00:39:22.071482

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72b8ab7e41ac'
down_revision: Union[str, Sequence[str], None] = 'd16404291a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_view',
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=50), server_default=sa.text("'cases'"), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('column_sizing', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_by', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.String(length=10), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_default_all', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_shared', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], name=op.f('fk_saved_view_agency_id_agency'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name=op.f('fk_saved_view_agent_id_agent'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_view'))
    )
    op.create_index(op.f('ix_saved_view_agency_id'), 'saved_view', ['agency_id'], unique=False)
    op.create_index(op.f('ix_saved_view_agent_id'), 'saved_view', ['agent_id'], unique=False)
    op.create_index(op.f('ix_saved_view_entity'), 'saved_view', ['entity'], unique=False)
    op.create_index('uq_saved_view_default_all', 'saved_view', ['agent_id', 'agency_id', 'entity'], unique=True, postgresql_where=sa.text('is_default_all'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_saved_view_default_all', table_name='saved_view', postgresql_where=sa.text('is_default_all'))
    op.drop_index(op.f('ix_saved_view_entity'), table_name='saved_view')
    op.drop_index(op.f('ix_saved_view_agent_id'), table_name='saved_view')
    op.drop_index(op.f('ix_saved_view_agency_id'), table_name='saved_view')
    op.drop_table('saved_view')
    # ### end Alembic commands ###
