"""step_requirements_and_completion_mode

Revision ID: 82e355266ed5
Revises: 91412f098b91
Create Date: 2026-06-13 16:11:52.594349

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e355266ed5'
down_revision: Union[str, Sequence[str], None] = '91412f098b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_requirement',
    sa.Column('step_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['journey_template_step.id'], name=op.f('fk_step_requirement_step_id_journey_template_step'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_step_requirement')),
    sa.UniqueConstraint('step_id', 'kind', 'reference', 'scope', name='uq_step_requirement')
    )
    op.create_index(op.f('ix_step_requirement_step_id'), 'step_requirement', ['step_id'], unique=False)
    op.create_table('case_step_requirement',
    sa.Column('case_step_progress_id', sa.Uuid(), nullable=False),
    sa.Column('step_requirement_id', sa.Uuid(), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_step_progress_id'], ['case_step_progress.id'], name=op.f('fk_case_step_requirement_case_step_progress_id_case_step_progress'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_case_step_requirement_document_id_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['case_person.id'], name=op.f('fk_case_step_requirement_person_id_case_person'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_requirement_id'], ['step_requirement.id'], name=op.f('fk_case_step_requirement_step_requirement_id_step_requirement'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_step_requirement')),
    sa.UniqueConstraint('case_step_progress_id', 'person_id', 'kind', 'reference', name='uq_case_step_requirement')
    )
    op.create_index(op.f('ix_case_step_requirement_case_step_progress_id'), 'case_step_requirement', ['case_step_progress_id'], unique=False)
    op.create_index(op.f('ix_case_step_requirement_person_id'), 'case_step_requirement', ['person_id'], unique=False)
    op.create_index(op.f('ix_case_step_requirement_step_requirement_id'), 'case_step_requirement', ['step_requirement_id'], unique=False)
    op.add_column('journey_template_step', sa.Column('completion_mode', sa.String(length=20), server_default=sa.text("'agency_validation'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journey_template_step', 'completion_mode')
    op.drop_index(op.f('ix_case_step_requirement_step_requirement_id'), table_name='case_step_requirement')
    op.drop_index(op.f('ix_case_step_requirement_person_id'), table_name='case_step_requirement')
    op.drop_index(op.f('ix_case_step_requirement_case_step_progress_id'), table_name='case_step_requirement')
    op.drop_table('case_step_requirement')
    op.drop_index(op.f('ix_step_requirement_step_id'), table_name='step_requirement')
    op.drop_table('step_requirement')
    # ### end Alembic commands ###
