"""remove_residence_permit_number

Revision ID: 91412f098b91
Revises: f289745cdb2a
Create Date: 2026-06-13 14:38:36.657775

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91412f098b91'
down_revision: Union[str, Sequence[str], None] = 'f289745cdb2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_person', 'residence_permit_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_person', sa.Column('residence_permit_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
