"""create_all_tables

Revision ID: af9ddfd8f3b9
Revises: 
Create Date: 2026-06-10 13:14:11.424355

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af9ddfd8f3b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agency'))
    )
    op.create_index(op.f('ix_agency_slug'), 'agency', ['slug'], unique=True)
    op.create_table('expat_user',
    sa.Column('preferred_lang', sa.String(length=5), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expat_user'))
    )
    op.create_index(op.f('ix_expat_user_email'), 'expat_user', ['email'], unique=True)
    op.create_table('permission',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission'))
    )
    op.create_index(op.f('ix_permission_key'), 'permission', ['key'], unique=True)
    op.create_table('agent',
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], name=op.f('fk_agent_agency_id_agency'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent'))
    )
    op.create_index(op.f('ix_agent_agency_id'), 'agent', ['agency_id'], unique=False)
    op.create_index(op.f('ix_agent_email'), 'agent', ['email'], unique=True)
    op.create_table('journey_template',
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], name=op.f('fk_journey_template_agency_id_agency'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journey_template'))
    )
    op.create_index(op.f('ix_journey_template_agency_id'), 'journey_template', ['agency_id'], unique=False)
    op.create_table('message_template',
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], name=op.f('fk_message_template_agency_id_agency'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_template'))
    )
    op.create_index(op.f('ix_message_template_agency_id'), 'message_template', ['agency_id'], unique=False)
    op.create_table('protected_resource',
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=False),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(audience = 'agent' AND permission_id IS NOT NULL) OR (audience IN ('public', 'expat') AND permission_id IS NULL)", name=op.f('ck_protected_resource_audience_permission_coherence')),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name=op.f('fk_protected_resource_permission_id_permission'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_protected_resource')),
    sa.UniqueConstraint('method', 'route', name=op.f('uq_protected_resource_method'))
    )
    op.create_table('role',
    sa.Column('agency_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], name=op.f('fk_role_agency_id_agency'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('agency_id', 'name', name=op.f('uq_role_agency_id'), postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_role_agency_id'), 'role', ['agency_id'], unique=False)
    op.create_table('agent_invitation',
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invited_by_agent_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], name=op.f('fk_agent_invitation_agency_id_agency'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_agent_id'], ['agent.id'], name=op.f('fk_agent_invitation_invited_by_agent_id_agent'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_agent_invitation_role_id_role'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_invitation'))
    )
    op.create_index(op.f('ix_agent_invitation_agency_id'), 'agent_invitation', ['agency_id'], unique=False)
    op.create_index(op.f('ix_agent_invitation_email'), 'agent_invitation', ['email'], unique=False)
    op.create_index(op.f('ix_agent_invitation_token'), 'agent_invitation', ['token'], unique=True)
    op.create_table('agent_role',
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name=op.f('fk_agent_role_agent_id_agent'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_agent_role_role_id_role'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'role_id', name=op.f('pk_agent_role'))
    )
    op.create_table('client_case',
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('principal_expat_user_id', sa.Uuid(), nullable=False),
    sa.Column('owner_agent_id', sa.Uuid(), nullable=True),
    sa.Column('journey_template_id', sa.Uuid(), nullable=True),
    sa.Column('origin_country', sa.String(length=2), nullable=True),
    sa.Column('dest_country', sa.String(length=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], name=op.f('fk_client_case_agency_id_agency'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journey_template_id'], ['journey_template.id'], name=op.f('fk_client_case_journey_template_id_journey_template'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_agent_id'], ['agent.id'], name=op.f('fk_client_case_owner_agent_id_agent'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['principal_expat_user_id'], ['expat_user.id'], name=op.f('fk_client_case_principal_expat_user_id_expat_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_case'))
    )
    op.create_index(op.f('ix_client_case_agency_id'), 'client_case', ['agency_id'], unique=False)
    op.create_index(op.f('ix_client_case_owner_agent_id'), 'client_case', ['owner_agent_id'], unique=False)
    op.create_index(op.f('ix_client_case_principal_expat_user_id'), 'client_case', ['principal_expat_user_id'], unique=False)
    op.create_index(op.f('ix_client_case_status'), 'client_case', ['status'], unique=False)
    op.create_table('journey_template_step',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('estimated_days', sa.Integer(), nullable=True),
    sa.Column('default_responsible_type', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['journey_template.id'], name=op.f('fk_journey_template_step_template_id_journey_template'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journey_template_step')),
    sa.UniqueConstraint('template_id', 'position', name=op.f('uq_journey_template_step_template_id'))
    )
    op.create_index(op.f('ix_journey_template_step_template_id'), 'journey_template_step', ['template_id'], unique=False)
    op.create_table('role_permission',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name=op.f('fk_role_permission_permission_id_permission'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_role_permission_role_id_role'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permission'))
    )
    op.create_table('activity_log',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['client_case.id'], name=op.f('fk_activity_log_case_id_client_case'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_log'))
    )
    op.create_index('ix_activity_log_case_id_created_at', 'activity_log', ['case_id', 'created_at'], unique=False)
    op.create_table('case_invitation',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['client_case.id'], name=op.f('fk_case_invitation_case_id_client_case'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_invitation'))
    )
    op.create_index(op.f('ix_case_invitation_case_id'), 'case_invitation', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_invitation_email'), 'case_invitation', ['email'], unique=False)
    op.create_index(op.f('ix_case_invitation_token'), 'case_invitation', ['token'], unique=True)
    op.create_table('case_note',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('author_agent_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_agent_id'], ['agent.id'], name=op.f('fk_case_note_author_agent_id_agent'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['client_case.id'], name=op.f('fk_case_note_case_id_client_case'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_note'))
    )
    op.create_index(op.f('ix_case_note_case_id'), 'case_note', ['case_id'], unique=False)
    op.create_table('external_contact',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['client_case.id'], name=op.f('fk_external_contact_case_id_client_case'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_contact'))
    )
    op.create_index(op.f('ix_external_contact_case_id'), 'external_contact', ['case_id'], unique=False)
    op.create_table('family_member',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['client_case.id'], name=op.f('fk_family_member_case_id_client_case'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_family_member'))
    )
    op.create_index(op.f('ix_family_member_case_id'), 'family_member', ['case_id'], unique=False)
    op.create_table('step_prerequisite',
    sa.Column('step_id', sa.Uuid(), nullable=False),
    sa.Column('prerequisite_step_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('step_id != prerequisite_step_id', name=op.f('ck_step_prerequisite_no_self_prerequisite')),
    sa.ForeignKeyConstraint(['prerequisite_step_id'], ['journey_template_step.id'], name=op.f('fk_step_prerequisite_prerequisite_step_id_journey_template_step'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['journey_template_step.id'], name=op.f('fk_step_prerequisite_step_id_journey_template_step'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id', 'prerequisite_step_id', name=op.f('pk_step_prerequisite'))
    )
    op.create_table('case_step_progress',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('template_step_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible_type', sa.String(length=20), nullable=True),
    sa.Column('responsible_agent_id', sa.Uuid(), nullable=True),
    sa.Column('responsible_external_id', sa.Uuid(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_agent_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(responsible_type IS NULL AND responsible_agent_id IS NULL AND responsible_external_id IS NULL) OR (responsible_type = 'agent' AND responsible_agent_id IS NOT NULL AND responsible_external_id IS NULL) OR (responsible_type = 'expat' AND responsible_agent_id IS NULL AND responsible_external_id IS NULL) OR (responsible_type = 'external' AND responsible_external_id IS NOT NULL AND responsible_agent_id IS NULL)", name=op.f('ck_case_step_progress_responsible_type_matches_fk')),
    sa.ForeignKeyConstraint(['case_id'], ['client_case.id'], name=op.f('fk_case_step_progress_case_id_client_case'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['completed_by_agent_id'], ['agent.id'], name=op.f('fk_case_step_progress_completed_by_agent_id_agent'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responsible_agent_id'], ['agent.id'], name=op.f('fk_case_step_progress_responsible_agent_id_agent')),
    sa.ForeignKeyConstraint(['responsible_external_id'], ['external_contact.id'], name=op.f('fk_case_step_progress_responsible_external_id_external_contact')),
    sa.ForeignKeyConstraint(['template_step_id'], ['journey_template_step.id'], name=op.f('fk_case_step_progress_template_step_id_journey_template_step'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_step_progress')),
    sa.UniqueConstraint('case_id', 'template_step_id', name=op.f('uq_case_step_progress_case_id'))
    )
    op.create_index(op.f('ix_case_step_progress_case_id'), 'case_step_progress', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_step_progress_template_step_id'), 'case_step_progress', ['template_step_id'], unique=False)
    op.create_table('document',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('step_progress_id', sa.Uuid(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by_type', sa.String(length=20), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['client_case.id'], name=op.f('fk_document_case_id_client_case'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_progress_id'], ['case_step_progress.id'], name=op.f('fk_document_step_progress_id_case_step_progress'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    op.create_index(op.f('ix_document_case_id'), 'document', ['case_id'], unique=False)
    op.create_table('reminder',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('step_progress_id', sa.Uuid(), nullable=True),
    sa.Column('message_template_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recipient_type', sa.String(length=20), nullable=False),
    sa.Column('recipient_external_id', sa.Uuid(), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('approved_by_agent_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(recipient_type = 'expat' AND recipient_external_id IS NULL) OR (recipient_type = 'external' AND recipient_external_id IS NOT NULL)", name=op.f('ck_reminder_recipient_type_matches_fk')),
    sa.ForeignKeyConstraint(['approved_by_agent_id'], ['agent.id'], name=op.f('fk_reminder_approved_by_agent_id_agent'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['client_case.id'], name=op.f('fk_reminder_case_id_client_case'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_template_id'], ['message_template.id'], name=op.f('fk_reminder_message_template_id_message_template'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_external_id'], ['external_contact.id'], name=op.f('fk_reminder_recipient_external_id_external_contact')),
    sa.ForeignKeyConstraint(['step_progress_id'], ['case_step_progress.id'], name=op.f('fk_reminder_step_progress_id_case_step_progress'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminder'))
    )
    op.create_index(op.f('ix_reminder_case_id'), 'reminder', ['case_id'], unique=False)
    op.create_index('ix_reminder_status_scheduled_at', 'reminder', ['status', 'scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reminder_status_scheduled_at', table_name='reminder')
    op.drop_index(op.f('ix_reminder_case_id'), table_name='reminder')
    op.drop_table('reminder')
    op.drop_index(op.f('ix_document_case_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_case_step_progress_template_step_id'), table_name='case_step_progress')
    op.drop_index(op.f('ix_case_step_progress_case_id'), table_name='case_step_progress')
    op.drop_table('case_step_progress')
    op.drop_table('step_prerequisite')
    op.drop_index(op.f('ix_family_member_case_id'), table_name='family_member')
    op.drop_table('family_member')
    op.drop_index(op.f('ix_external_contact_case_id'), table_name='external_contact')
    op.drop_table('external_contact')
    op.drop_index(op.f('ix_case_note_case_id'), table_name='case_note')
    op.drop_table('case_note')
    op.drop_index(op.f('ix_case_invitation_token'), table_name='case_invitation')
    op.drop_index(op.f('ix_case_invitation_email'), table_name='case_invitation')
    op.drop_index(op.f('ix_case_invitation_case_id'), table_name='case_invitation')
    op.drop_table('case_invitation')
    op.drop_index('ix_activity_log_case_id_created_at', table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_journey_template_step_template_id'), table_name='journey_template_step')
    op.drop_table('journey_template_step')
    op.drop_index(op.f('ix_client_case_status'), table_name='client_case')
    op.drop_index(op.f('ix_client_case_principal_expat_user_id'), table_name='client_case')
    op.drop_index(op.f('ix_client_case_owner_agent_id'), table_name='client_case')
    op.drop_index(op.f('ix_client_case_agency_id'), table_name='client_case')
    op.drop_table('client_case')
    op.drop_table('agent_role')
    op.drop_index(op.f('ix_agent_invitation_token'), table_name='agent_invitation')
    op.drop_index(op.f('ix_agent_invitation_email'), table_name='agent_invitation')
    op.drop_index(op.f('ix_agent_invitation_agency_id'), table_name='agent_invitation')
    op.drop_table('agent_invitation')
    op.drop_index(op.f('ix_role_agency_id'), table_name='role')
    op.drop_table('role')
    op.drop_table('protected_resource')
    op.drop_index(op.f('ix_message_template_agency_id'), table_name='message_template')
    op.drop_table('message_template')
    op.drop_index(op.f('ix_journey_template_agency_id'), table_name='journey_template')
    op.drop_table('journey_template')
    op.drop_index(op.f('ix_agent_email'), table_name='agent')
    op.drop_index(op.f('ix_agent_agency_id'), table_name='agent')
    op.drop_table('agent')
    op.drop_index(op.f('ix_permission_key'), table_name='permission')
    op.drop_table('permission')
    op.drop_index(op.f('ix_expat_user_email'), table_name='expat_user')
    op.drop_table('expat_user')
    op.drop_index(op.f('ix_agency_slug'), table_name='agency')
    op.drop_table('agency')
    # ### end Alembic commands ###
