"""add_auth_token_tables_and_relax_agent_binding_check

Revision ID: ccedc32e8ea6
Revises: af9ddfd8f3b9
Create Date: 2026-06-10 14:01:59.239173

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccedc32e8ea6'
down_revision: Union[str, Sequence[str], None] = 'af9ddfd8f3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_token',
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_token'))
    )
    op.create_index(op.f('ix_password_reset_token_token'), 'password_reset_token', ['token'], unique=True)
    op.create_table('refresh_token',
    sa.Column('jti', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('jti', name=op.f('pk_refresh_token'))
    )
    op.create_index('ix_refresh_token_actor', 'refresh_token', ['actor_type', 'actor_id'], unique=False)
    # ### end Alembic commands ###

    # MANUAL (autogenerate does not diff CHECK constraints): relax the
    # agent-binding check — audience='agent' may now carry a NULL
    # permission (= any authenticated agent, e.g. /me, /logout),
    # symmetric with the EXPAT audience.
    op.drop_constraint(
        op.f('ck_protected_resource_audience_permission_coherence'),
        'protected_resource',
        type_='check',
    )
    op.create_check_constraint(
        'audience_permission_coherence',
        'protected_resource',
        "(audience IN ('public', 'expat') AND permission_id IS NULL)"
        " OR audience = 'agent'",
    )


def downgrade() -> None:
    # MANUAL: restore the strict agent-binding check. Will fail if
    # AGENT bindings with NULL permission exist — expected: those rows
    # are invalid under the old contract and must be handled first.
    op.drop_constraint(
        op.f('ck_protected_resource_audience_permission_coherence'),
        'protected_resource',
        type_='check',
    )
    op.create_check_constraint(
        'audience_permission_coherence',
        'protected_resource',
        "(audience = 'agent' AND permission_id IS NOT NULL)"
        " OR (audience IN ('public', 'expat') AND permission_id IS NULL)",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_token_actor', table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_password_reset_token_token'), table_name='password_reset_token')
    op.drop_table('password_reset_token')
    # ### end Alembic commands ###
