"""add_impersonation_log

Revision ID: d6565cf1841f
Revises: e99dbcdf58b8
Create Date: 2026-06-11 20:27:06.372042

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6565cf1841f'
down_revision: Union[str, Sequence[str], None] = 'e99dbcdf58b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impersonation_log',
    sa.Column('impersonator_agent_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['impersonator_agent_id'], ['agent.id'], name=op.f('fk_impersonation_log_impersonator_agent_id_agent'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_impersonation_log'))
    )
    op.create_index(op.f('ix_impersonation_log_impersonator_agent_id'), 'impersonation_log', ['impersonator_agent_id'], unique=False)
    op.create_index(op.f('ix_impersonation_log_target_id'), 'impersonation_log', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_impersonation_log_target_id'), table_name='impersonation_log')
    op.drop_index(op.f('ix_impersonation_log_impersonator_agent_id'), table_name='impersonation_log')
    op.drop_table('impersonation_log')
    # ### end Alembic commands ###
