"""unified_case_person_and_addresses

Revision ID: de687433439a
Revises: 140ca9079e15
Create Date: 2026-06-13 13:42:22.486382

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de687433439a'
down_revision: Union[str, Sequence[str], None] = '140ca9079e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_person',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('expat_user_id', sa.Uuid(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('place_of_birth', sa.String(length=200), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('residence_permit_number', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['client_case.id'], name=op.f('fk_case_person_case_id_client_case'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expat_user_id'], ['expat_user.id'], name=op.f('fk_case_person_expat_user_id_expat_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_person'))
    )
    op.create_index(op.f('ix_case_person_case_id'), 'case_person', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_person_expat_user_id'), 'case_person', ['expat_user_id'], unique=False)
    op.create_index('uq_case_person_principal', 'case_person', ['case_id'], unique=True, postgresql_where=sa.text("kind = 'principal'"))

    # --- DATA MIGRATION (before dropping family_member) ---------------------
    # One PRINCIPAL row per case, linked to its expat_user (NOT filtered
    # on deleted_at — a soft-deleted case keeps its principal so it stays
    # coherent if restored). gen_random_uuid() is native on PG13+.
    op.execute(
        """
        INSERT INTO case_person (id, case_id, kind, expat_user_id, created_at, updated_at)
        SELECT gen_random_uuid(), c.id, 'principal', c.principal_expat_user_id, now(), now()
        FROM client_case c
        """
    )
    # Each family_member becomes a FAMILY person, name/relationship/
    # timestamps preserved (zero loss).
    op.execute(
        """
        INSERT INTO case_person
            (id, case_id, kind, full_name, relationship, created_at, updated_at)
        SELECT gen_random_uuid(), fm.case_id, 'family', fm.name, fm.relationship,
               fm.created_at, fm.updated_at
        FROM family_member fm
        """
    )

    op.drop_index(op.f('ix_family_member_case_id'), table_name='family_member')
    op.drop_table('family_member')
    op.add_column('client_case', sa.Column('origin_street', sa.String(length=255), nullable=True))
    op.add_column('client_case', sa.Column('origin_city', sa.String(length=100), nullable=True))
    op.add_column('client_case', sa.Column('origin_postal_code', sa.String(length=20), nullable=True))
    op.add_column('client_case', sa.Column('dest_street', sa.String(length=255), nullable=True))
    op.add_column('client_case', sa.Column('dest_city', sa.String(length=100), nullable=True))
    op.add_column('client_case', sa.Column('dest_postal_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_case', 'dest_postal_code')
    op.drop_column('client_case', 'dest_city')
    op.drop_column('client_case', 'dest_street')
    op.drop_column('client_case', 'origin_postal_code')
    op.drop_column('client_case', 'origin_city')
    op.drop_column('client_case', 'origin_street')
    op.create_table('family_member',
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('relationship', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['client_case.id'], name=op.f('fk_family_member_case_id_client_case'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_family_member'))
    )
    op.create_index(op.f('ix_family_member_case_id'), 'family_member', ['case_id'], unique=False)
    # Re-fill family_member from the FAMILY persons (PRINCIPAL rows have
    # no family_member equivalent and are dropped with the table).
    op.execute(
        """
        INSERT INTO family_member (id, case_id, name, relationship, created_at, updated_at)
        SELECT gen_random_uuid(), cp.case_id, cp.full_name, cp.relationship,
               cp.created_at, cp.updated_at
        FROM case_person cp
        WHERE cp.kind = 'family'
        """
    )
    op.drop_index('uq_case_person_principal', table_name='case_person', postgresql_where=sa.text("kind = 'principal'"))
    op.drop_index(op.f('ix_case_person_expat_user_id'), table_name='case_person')
    op.drop_index(op.f('ix_case_person_case_id'), table_name='case_person')
    op.drop_table('case_person')
    # ### end Alembic commands ###
