"""add_required_documents_to_journey_template_step

Revision ID: e99dbcdf58b8
Revises: eda57f1e85da
Create Date: 2026-06-11 11:14:42.297556

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e99dbcdf58b8'
down_revision: Union[str, Sequence[str], None] = 'eda57f1e85da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journey_template_step', sa.Column('required_documents', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journey_template_step', 'required_documents')
    # ### end Alembic commands ###
