"""add_job_tables_and_reminder_auto_threshold

Revision ID: eda57f1e85da
Revises: ccedc32e8ea6
Create Date: 2026-06-10 19:04:21.656702

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eda57f1e85da'
down_revision: Union[str, Sequence[str], None] = 'ccedc32e8ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_config',
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('paused_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_status', sa.String(length=20), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_config'))
    )
    op.create_index(op.f('ix_job_config_job_id'), 'job_config', ['job_id'], unique=True)
    op.create_table('job_run',
    sa.Column('job_config_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('log_output', sa.Text(), nullable=False),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('triggered_by_agent_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['job_config_id'], ['job_config.id'], name=op.f('fk_job_run_job_config_id_job_config'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_agent_id'], ['agent.id'], name=op.f('fk_job_run_triggered_by_agent_id_agent'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_run'))
    )
    op.create_index(op.f('ix_job_run_job_config_id'), 'job_run', ['job_config_id'], unique=False)
    op.add_column('reminder', sa.Column('auto_threshold_days', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_reminder_step_progress_id'), 'reminder', ['step_progress_id', 'auto_threshold_days'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_reminder_step_progress_id'), 'reminder', type_='unique')
    op.drop_column('reminder', 'auto_threshold_days')
    op.drop_index(op.f('ix_job_run_job_config_id'), table_name='job_run')
    op.drop_table('job_run')
    op.drop_index(op.f('ix_job_config_job_id'), table_name='job_config')
    op.drop_table('job_config')
    # ### end Alembic commands ###
