"""add_custom_field_definitions_and_person_custom_fields

Revision ID: f289745cdb2a
Revises: de687433439a
Create Date: 2026-06-13 14:01:31.818492

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f289745cdb2a'
down_revision: Union[str, Sequence[str], None] = 'de687433439a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_field_definition',
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], name=op.f('fk_custom_field_definition_agency_id_agency'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_field_definition')),
    sa.UniqueConstraint('agency_id', 'key', name='uq_custom_field_agency_key')
    )
    op.create_index('ix_custom_field_agency_active', 'custom_field_definition', ['agency_id', 'archived_at'], unique=False)
    op.create_index(op.f('ix_custom_field_definition_agency_id'), 'custom_field_definition', ['agency_id'], unique=False)
    op.add_column('case_person', sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_person', 'custom_fields')
    op.drop_index(op.f('ix_custom_field_definition_agency_id'), table_name='custom_field_definition')
    op.drop_index('ix_custom_field_agency_active', table_name='custom_field_definition')
    op.drop_table('custom_field_definition')
    # ### end Alembic commands ###
