"""Section-types + field-preset catalog (samples phase B) — THE back-side
source of truth.

The 11 ready-made sections and their field presets, with labels (and
select options) in the 6 product languages. Mirrored from the frontend
catalog (nidria-frontend/src/lib/sectionTemplates.ts + fieldCatalog.ts +
locales/*/catalog.json — pointer documented there); the BACK copy is the
reference: the sample seed instantiates sections/fields from it, and
clone_template materializes the missing custom_field_definition rows of
the cloning agency from it (label in the agency language + full
label_i18n; options in the agency language — the definition model has no
per-language options).

Native fields (COLLECTABLE_BASE_FIELDS columns) attach as kind=base_field
and need no definition; every other key attaches as kind=custom_field."""

from dataclasses import dataclass, field

from src.core.enums import AgencySector
from src.progress.requirements_eval import COLLECTABLE_BASE_FIELDS

LANGS = ("fr", "en", "es", "ru", "pt", "it", "hu")


@dataclass(frozen=True)
class CatalogFieldPreset:
    key: str
    field_type: str
    labels: dict[str, str]  # per language, the 6 complete
    options: dict[str, list[str]] | None  # per language, select types only


@dataclass(frozen=True)
class SectionType:
    key: str
    labels: dict[str, str]
    field_keys: tuple[str, ...]  # ordered; native OR preset keys
    # Sector packs: the business sectors this section is offered for (the
    # front pre-checks / sorts the section picker with it). () = universal
    # (identity, language, contact — shown for every sector). Additive: no
    # existing field_keys touched, no migration (pure code catalog).
    sectors: tuple[AgencySector, ...] = field(default=())


SECTION_TYPES: dict[str, SectionType] = {
    "identity": SectionType(
        key="identity",
        labels={
            "fr": "Identité",
            "en": "Identity",
            "es": "Identidad",
            "ru": "Идентификация",
            "pt": "Identidade",
            "it": "Identità",
            "hu": "Személyazonosság",
        },
        field_keys=(
            "passport_number",
            "date_of_birth",
            "nationality",
            "place_of_birth",
            "sex",
            "birth_country",
            "second_nationality",
            "residence_address",
        ),
    ),
    "family_situation": SectionType(
        key="family_situation",
        sectors=(AgencySector.WEALTH,),
        labels={
            "fr": "Situation familiale",
            "en": "Family situation",
            "es": "Situación familiar",
            "ru": "Семейное положение",
            "pt": "Estado civil",
            "it": "Stato civile",
            "hu": "Családi helyzet",
        },
        field_keys=(
            "marital_status",
            "spouse_name",
            "spouse_nationality",
            "spouse_birth_date",
            "children_count",
            "dependents",
            "matrimonial_regime",
        ),
    ),
    "immigration": SectionType(
        key="immigration",
        sectors=(AgencySector.IMMIGRATION, AgencySector.HR_MOBILITY, AgencySector.LEGAL),
        labels={
            "fr": "Immigration & séjour",
            "en": "Immigration & residence",
            "es": "Inmigración y estancia",
            "ru": "Иммиграция и пребывание",
            "pt": "Imigração e residência",
            "it": "Immigrazione e soggiorno",
            "hu": "Bevándorlás és tartózkodás",
        },
        field_keys=(
            "visa_type",
            "visa_number",
            "immigration_status",
            "residence_permit_number",
            "passport_expiry",
            "visa_permit_expiry",
            "consular_appointment_date",
        ),
    ),
    "professional": SectionType(
        key="professional",
        sectors=(AgencySector.HR_MOBILITY,),
        labels={
            "fr": "Situation professionnelle",
            "en": "Professional situation",
            "es": "Situación profesional",
            "ru": "Профессиональная деятельность",
            "pt": "Situação profissional",
            "it": "Situazione professionale",
            "hu": "Szakmai helyzet",
        },
        field_keys=(
            "profession",
            "employer",
            "job_title",
            "industry",
            "contract_type",
            "activity_status",
            "contract_start_date",
        ),
    ),
    "company": SectionType(
        key="company",
        sectors=(AgencySector.LEGAL, AgencySector.ACCOUNTING),
        labels={
            "fr": "Création de société",
            "en": "Company formation",
            "es": "Creación de empresa",
            "ru": "Создание компании",
            "pt": "Constituição de sociedade",
            "it": "Costituzione di società",
            "hu": "Cégalapítás",
        },
        field_keys=(
            "company_name",
            "legal_form",
            "share_capital",
            "company_registration_number",
            "registration_date",
            "headquarters_address",
            "legal_representative_name",
            "partners_count",
        ),
    ),
    "housing": SectionType(
        key="housing",
        sectors=(AgencySector.HR_MOBILITY,),
        labels={
            "fr": "Logement",
            "en": "Housing",
            "es": "Vivienda",
            "ru": "Жильё",
            "pt": "Habitação",
            "it": "Alloggio",
            "hu": "Lakhatás",
        },
        field_keys=("housing_address", "housing_status", "property_type", "move_in_date"),
    ),
    "tax": SectionType(
        key="tax",
        sectors=(AgencySector.ACCOUNTING, AgencySector.WEALTH),
        labels={
            "fr": "Fiscalité",
            "en": "Taxation",
            "es": "Fiscalidad",
            "ru": "Налогообложение",
            "pt": "Fiscalidade",
            "it": "Fiscalità",
            "hu": "Adózás",
        },
        field_keys=(
            "tax_residence_country",
            "tax_id",
            "target_tax_regime",
            "origin_country_tax_filing",
            "tax_support_required",
        ),
    ),
    "language": SectionType(
        key="language",
        labels={
            "fr": "Langue & intégration",
            "en": "Language & integration",
            "es": "Idioma e integración",
            "ru": "Язык и интеграция",
            "pt": "Idioma e integração",
            "it": "Lingua e integrazione",
            "hu": "Nyelv és beilleszkedés",
        },
        field_keys=(
            "host_language_level",
            "native_language",
            "other_languages",
            "interpreter_needed",
        ),
    ),
    "education": SectionType(
        key="education",
        sectors=(AgencySector.HR_MOBILITY,),
        labels={
            "fr": "Éducation & scolarité",
            "en": "Education & schooling",
            "es": "Educación y escolaridad",
            "ru": "Образование и обучение",
            "pt": "Educação e escolaridade",
            "it": "Istruzione e scolarità",
            "hu": "Oktatás és iskoláztatás",
        },
        field_keys=(
            "education_level",
            "last_institution",
            "field_of_study",
            "diploma_recognition",
            "children_school_preference",
            "target_school_start_date",
        ),
    ),
    "vehicle": SectionType(
        key="vehicle",
        sectors=(AgencySector.HR_MOBILITY,),
        labels={
            "fr": "Véhicule & mobilité",
            "en": "Vehicle & mobility",
            "es": "Vehículo y movilidad",
            "ru": "Транспорт и мобильность",
            "pt": "Veículo e mobilidade",
            "it": "Veicolo e mobilità",
            "hu": "Jármű és mobilitás",
        },
        field_keys=(
            "has_vehicle_to_import",
            "vehicle_make_model",
            "vehicle_registration_number",
            "driving_license_number",
            "license_to_exchange",
            "license_country",
        ),
    ),
    "contact": SectionType(
        key="contact",
        labels={
            "fr": "Contact",
            "en": "Contact",
            "es": "Contacto",
            "ru": "Контакт",
            "pt": "Contacto",
            "it": "Contatto",
            "hu": "Kapcsolat",
        },
        field_keys=(
            "phone",
            "secondary_email",
            "whatsapp",
            "preferred_language",
            "preferred_contact_channel",
        ),
    ),
    # === Sector packs (bloc packs sectoriels) — new sections ==========================
    "real_estate_deal": SectionType(
        key="real_estate_deal",
        sectors=(AgencySector.REAL_ESTATE,),
        labels={
            "fr": "Transaction immobilière",
            "en": "Real estate transaction",
            "es": "Transacción inmobiliaria",
            "ru": "Сделка с недвижимостью",
            "pt": "Transação imobiliária",
            "it": "Transazione immobiliare",
            "hu": "Ingatlanügylet",
        },
        field_keys=(
            "property_deal_type",
            "property_kind",
            "property_address",
            "property_surface",
            "property_rooms",
            "property_price",
            "mandate_type",
            "mandate_number",
            "transaction_stage",
            "energy_performance",
            "expected_signing_date",
            "agency_fee_percent",
        ),
    ),
    "wealth_review": SectionType(
        key="wealth_review",
        sectors=(AgencySector.WEALTH,),
        labels={
            "fr": "Bilan patrimonial",
            "en": "Wealth review",
            "es": "Balance patrimonial",
            "ru": "Анализ капитала",
            "pt": "Balanço patrimonial",
            "it": "Bilancio patrimoniale",
            "hu": "Vagyoni áttekintés",
        },
        field_keys=(
            "risk_profile",
            "wealth_objective",
            "investment_horizon",
            "estimated_wealth",
            "savings_capacity",
            "funds_origin",
            "held_products",
            "esg_preference",
        ),
    ),
    "consulting_mission": SectionType(
        key="consulting_mission",
        sectors=(AgencySector.CONSULTING,),
        labels={
            "fr": "Mission de conseil",
            "en": "Consulting mission",
            "es": "Misión de consultoría",
            "ru": "Консалтинговый проект",
            "pt": "Missão de consultoria",
            "it": "Incarico di consulenza",
            "hu": "Tanácsadói megbízás",
        },
        field_keys=(
            "mission_type",
            "billing_mode",
            "daily_rate",
            "sold_budget",
            "sold_days",
            "completion_rate",
            "consumed_days",
            "expected_deliverables",
            "steering_committee_freq",
        ),
    ),
}

FIELD_PRESETS: dict[str, CatalogFieldPreset] = {
    "birth_country": CatalogFieldPreset(
        key="birth_country",
        field_type="country",
        labels={
            "fr": "Pays de naissance",
            "en": "Country of birth",
            "es": "País de nacimiento",
            "ru": "Страна рождения",
            "pt": "País de nascimento",
            "it": "Paese di nascita",
            "hu": "Születési ország",
        },
        options=None,
    ),
    "second_nationality": CatalogFieldPreset(
        key="second_nationality",
        field_type="country",
        labels={
            "fr": "Deuxième nationalité",
            "en": "Second nationality",
            "es": "Segunda nacionalidad",
            "ru": "Второе гражданство",
            "pt": "Segunda nacionalidade",
            "it": "Seconda nazionalità",
            "hu": "Második állampolgárság",
        },
        options=None,
    ),
    "residence_address": CatalogFieldPreset(
        key="residence_address",
        field_type="address",
        labels={
            "fr": "Adresse de résidence",
            "en": "Residence address",
            "es": "Dirección de residencia",
            "ru": "Адрес проживания",
            "pt": "Morada de residência",
            "it": "Indirizzo di residenza",
            "hu": "Lakcím",
        },
        options=None,
    ),
    "spouse_name": CatalogFieldPreset(
        key="spouse_name",
        field_type="text",
        labels={
            "fr": "Nom du conjoint",
            "en": "Spouse's name",
            "es": "Nombre del cónyuge",
            "ru": "Имя супруга(и)",
            "pt": "Nome do cônjuge",
            "it": "Nome del coniuge",
            "hu": "Házastárs neve",
        },
        options=None,
    ),
    "spouse_nationality": CatalogFieldPreset(
        key="spouse_nationality",
        field_type="country",
        labels={
            "fr": "Nationalité du conjoint",
            "en": "Spouse's nationality",
            "es": "Nacionalidad del cónyuge",
            "ru": "Гражданство супруга(и)",
            "pt": "Nacionalidade do cônjuge",
            "it": "Nazionalità del coniuge",
            "hu": "Házastárs állampolgársága",
        },
        options=None,
    ),
    "spouse_birth_date": CatalogFieldPreset(
        key="spouse_birth_date",
        field_type="date",
        labels={
            "fr": "Date de naissance du conjoint",
            "en": "Spouse's date of birth",
            "es": "Fecha de nacimiento del cónyuge",
            "ru": "Дата рождения супруга(и)",
            "pt": "Data de nascimento do cônjuge",
            "it": "Data di nascita del coniuge",
            "hu": "Házastárs születési dátuma",
        },
        options=None,
    ),
    "children_count": CatalogFieldPreset(
        key="children_count",
        field_type="number",
        labels={
            "fr": "Nombre d'enfants",
            "en": "Number of children",
            "es": "Número de hijos",
            "ru": "Количество детей",
            "pt": "Número de filhos",
            "it": "Numero di figli",
            "hu": "Gyermekek száma",
        },
        options=None,
    ),
    "dependents": CatalogFieldPreset(
        key="dependents",
        field_type="boolean",
        labels={
            "fr": "Personnes à charge",
            "en": "Dependents",
            "es": "Personas a cargo",
            "ru": "Иждивенцы",
            "pt": "Pessoas a cargo",
            "it": "Persone a carico",
            "hu": "Eltartottak",
        },
        options=None,
    ),
    "matrimonial_regime": CatalogFieldPreset(
        key="matrimonial_regime",
        field_type="text",
        labels={
            "fr": "Régime matrimonial",
            "en": "Matrimonial regime",
            "es": "Régimen matrimonial",
            "ru": "Брачный режим",
            "pt": "Regime de bens",
            "it": "Regime patrimoniale",
            "hu": "Házassági vagyonjogi rendszer",
        },
        options=None,
    ),
    "visa_type": CatalogFieldPreset(
        key="visa_type",
        field_type="select",
        labels={
            "fr": "Type de visa",
            "en": "Visa type",
            "es": "Tipo de visado",
            "ru": "Тип визы",
            "pt": "Tipo de visto",
            "it": "Tipo di visto",
            "hu": "Vízum típusa",
        },
        options={
            "fr": [
                "Court séjour",
                "Long séjour",
                "Travail",
                "Étudiant",
                "Regroupement familial",
                "Investisseur",
                "Retraité",
                "Autre",
            ],
            "en": [
                "Short stay",
                "Long stay",
                "Work",
                "Student",
                "Family reunification",
                "Investor",
                "Retiree",
                "Other",
            ],
            "es": [
                "Estancia corta",
                "Estancia larga",
                "Trabajo",
                "Estudiante",
                "Reagrupación familiar",
                "Inversor",
                "Jubilado",
                "Otro",
            ],
            "ru": [
                "Краткосрочная",
                "Долгосрочная",
                "Рабочая",
                "Студенческая",
                "Воссоединение семьи",
                "Инвесторская",
                "Пенсионная",
                "Другое",
            ],
            "pt": [
                "Curta duração",
                "Longa duração",
                "Trabalho",
                "Estudante",
                "Reagrupamento familiar",
                "Investidor",
                "Reformado",
                "Outro",
            ],
            "it": [
                "Breve soggiorno",
                "Lungo soggiorno",
                "Lavoro",
                "Studente",
                "Ricongiungimento familiare",
                "Investitore",
                "Pensionato",
                "Altro",
            ],
            "hu": [
                "Rövid tartózkodás",
                "Hosszú tartózkodás",
                "Munka",
                "Diák",
                "Családegyesítés",
                "Befektető",
                "Nyugdíjas",
                "Egyéb",
            ],
        },
    ),
    "visa_number": CatalogFieldPreset(
        key="visa_number",
        field_type="text",
        labels={
            "fr": "Numéro de visa",
            "en": "Visa number",
            "es": "Número de visado",
            "ru": "Номер визы",
            "pt": "Número de visto",
            "it": "Numero di visto",
            "hu": "Vízum száma",
        },
        options=None,
    ),
    "immigration_status": CatalogFieldPreset(
        key="immigration_status",
        field_type="select",
        labels={
            "fr": "Statut d'immigration actuel",
            "en": "Current immigration status",
            "es": "Estatus migratorio actual",
            "ru": "Текущий иммиграционный статус",
            "pt": "Estatuto de imigração atual",
            "it": "Stato di immigrazione attuale",
            "hu": "Jelenlegi bevándorlási státusz",
        },
        options={
            "fr": [
                "Touriste",
                "Résident temporaire",
                "Résident permanent",
                "En cours de demande",
                "Sans titre",
                "Autre",
            ],
            "en": [
                "Tourist",
                "Temporary resident",
                "Permanent resident",
                "Application pending",
                "Undocumented",
                "Other",
            ],
            "es": [
                "Turista",
                "Residente temporal",
                "Residente permanente",
                "Solicitud en trámite",
                "Sin documentación",
                "Otro",
            ],
            "ru": [
                "Турист",
                "Временный резидент",
                "Постоянный резидент",
                "В процессе подачи",
                "Без статуса",
                "Другое",
            ],
            "pt": [
                "Turista",
                "Residente temporário",
                "Residente permanente",
                "Pedido em curso",
                "Sem título",
                "Outro",
            ],
            "it": [
                "Turista",
                "Residente temporaneo",
                "Residente permanente",
                "Domanda in corso",
                "Senza titolo",
                "Altro",
            ],
            "hu": [
                "Turista",
                "Ideiglenes lakos",
                "Állandó lakos",
                "Folyamatban lévő kérelem",
                "Engedély nélkül",
                "Egyéb",
            ],
        },
    ),
    "residence_permit_number": CatalogFieldPreset(
        key="residence_permit_number",
        field_type="text",
        labels={
            "fr": "Numéro de titre de séjour",
            "en": "Residence permit number",
            "es": "Número de permiso de residencia",
            "ru": "Номер вида на жительство",
            "pt": "Número de título de residência",
            "it": "Numero del permesso di soggiorno",
            "hu": "Tartózkodási engedély száma",
        },
        options=None,
    ),
    "passport_expiry": CatalogFieldPreset(
        key="passport_expiry",
        field_type="date",
        labels={
            "fr": "Date d'expiration du passeport",
            "en": "Passport expiry date",
            "es": "Fecha de caducidad del pasaporte",
            "ru": "Дата истечения паспорта",
            "pt": "Data de validade do passaporte",
            "it": "Data di scadenza del passaporto",
            "hu": "Útlevél lejárati dátuma",
        },
        options=None,
    ),
    "visa_permit_expiry": CatalogFieldPreset(
        key="visa_permit_expiry",
        field_type="date",
        labels={
            "fr": "Date d'expiration du visa / titre",
            "en": "Visa / permit expiry date",
            "es": "Fecha de caducidad del visado / permiso",
            "ru": "Дата истечения визы / разрешения",
            "pt": "Data de validade do visto / título",
            "it": "Data di scadenza del visto / permesso",
            "hu": "Vízum / engedély lejárati dátuma",
        },
        options=None,
    ),
    "consular_appointment_date": CatalogFieldPreset(
        key="consular_appointment_date",
        field_type="date",
        labels={
            "fr": "Date de rendez-vous consulaire",
            "en": "Consular appointment date",
            "es": "Fecha de cita consular",
            "ru": "Дата приёма в консульстве",
            "pt": "Data de marcação consular",
            "it": "Data dell'appuntamento consolare",
            "hu": "Konzuli időpont dátuma",
        },
        options=None,
    ),
    "job_title": CatalogFieldPreset(
        key="job_title",
        field_type="text",
        labels={
            "fr": "Intitulé du poste",
            "en": "Job title",
            "es": "Puesto de trabajo",
            "ru": "Должность",
            "pt": "Designação do cargo",
            "it": "Qualifica professionale",
            "hu": "Munkakör megnevezése",
        },
        options=None,
    ),
    "industry": CatalogFieldPreset(
        key="industry",
        field_type="text",
        labels={
            "fr": "Secteur d'activité",
            "en": "Industry",
            "es": "Sector de actividad",
            "ru": "Отрасль деятельности",
            "pt": "Setor de atividade",
            "it": "Settore di attività",
            "hu": "Ágazat",
        },
        options=None,
    ),
    "contract_type": CatalogFieldPreset(
        key="contract_type",
        field_type="text",
        labels={
            "fr": "Type de contrat",
            "en": "Contract type",
            "es": "Tipo de contrato",
            "ru": "Тип договора",
            "pt": "Tipo de contrato",
            "it": "Tipo di contratto",
            "hu": "Szerződés típusa",
        },
        options=None,
    ),
    "activity_status": CatalogFieldPreset(
        key="activity_status",
        field_type="select",
        labels={
            "fr": "Statut d'activité",
            "en": "Activity status",
            "es": "Situación laboral",
            "ru": "Статус деятельности",
            "pt": "Estatuto de atividade",
            "it": "Stato dell'attività",
            "hu": "Tevékenységi státusz",
        },
        options={
            "fr": [
                "Salarié",
                "Indépendant",
                "Chef d'entreprise",
                "Retraité",
                "Étudiant",
                "Sans activité",
            ],
            "en": [
                "Employee",
                "Self-employed",
                "Business owner",
                "Retired",
                "Student",
                "Not working",
            ],
            "es": [
                "Asalariado",
                "Autónomo",
                "Empresario",
                "Jubilado",
                "Estudiante",
                "Sin actividad",
            ],
            "ru": [
                "Наёмный работник",
                "Самозанятый",
                "Руководитель компании",
                "Пенсионер",
                "Студент",
                "Без деятельности",
            ],
            "pt": [
                "Trabalhador por conta de outrem",
                "Trabalhador independente",
                "Empresário",
                "Reformado",
                "Estudante",
                "Sem atividade",
            ],
            "it": [
                "Lavoratore dipendente",
                "Lavoratore autonomo",
                "Imprenditore",
                "Pensionato",
                "Studente",
                "Senza attività",
            ],
            "hu": [
                "Alkalmazott",
                "Egyéni vállalkozó",
                "Cégvezető",
                "Nyugdíjas",
                "Diák",
                "Nem aktív",
            ],
        },
    ),
    "contract_start_date": CatalogFieldPreset(
        key="contract_start_date",
        field_type="date",
        labels={
            "fr": "Date de début du contrat",
            "en": "Contract start date",
            "es": "Fecha de inicio del contrato",
            "ru": "Дата начала договора",
            "pt": "Data de início do contrato",
            "it": "Data di inizio del contratto",
            "hu": "Szerződés kezdete",
        },
        options=None,
    ),
    "company_name": CatalogFieldPreset(
        key="company_name",
        field_type="text",
        labels={
            "fr": "Raison sociale",
            "en": "Company name",
            "es": "Razón social",
            "ru": "Наименование компании",
            "pt": "Denominação social",
            "it": "Ragione sociale",
            "hu": "Cégnév",
        },
        options=None,
    ),
    "legal_form": CatalogFieldPreset(
        key="legal_form",
        field_type="text",
        labels={
            "fr": "Forme juridique",
            "en": "Legal form",
            "es": "Forma jurídica",
            "ru": "Организационно-правовая форма",
            "pt": "Forma jurídica",
            "it": "Forma giuridica",
            "hu": "Jogi forma",
        },
        options=None,
    ),
    "share_capital": CatalogFieldPreset(
        key="share_capital",
        field_type="number",
        labels={
            "fr": "Capital social",
            "en": "Share capital",
            "es": "Capital social",
            "ru": "Уставный капитал",
            "pt": "Capital social",
            "it": "Capitale sociale",
            "hu": "Törzstőke",
        },
        options=None,
    ),
    "company_registration_number": CatalogFieldPreset(
        key="company_registration_number",
        field_type="text",
        labels={
            "fr": "Numéro d'immatriculation (SIRET / RUC / NIF…)",
            "en": "Registration number (SIRET / RUC / NIF…)",
            "es": "Número de registro (SIRET / RUC / NIF…)",
            "ru": "Регистрационный номер (SIRET / RUC / NIF…)",
            "pt": "Número de registo (NIPC / SIRET / RUC…)",
            "it": "Numero di registrazione (SIRET / RUC / NIF…)",
            "hu": "Cégjegyzékszám (SIRET / RUC / NIF…)",
        },
        options=None,
    ),
    "registration_date": CatalogFieldPreset(
        key="registration_date",
        field_type="date",
        labels={
            "fr": "Date d'immatriculation",
            "en": "Registration date",
            "es": "Fecha de registro",
            "ru": "Дата регистрации",
            "pt": "Data de registo",
            "it": "Data di registrazione",
            "hu": "Bejegyzés dátuma",
        },
        options=None,
    ),
    "headquarters_address": CatalogFieldPreset(
        key="headquarters_address",
        field_type="address",
        labels={
            "fr": "Adresse du siège social",
            "en": "Registered office address",
            "es": "Domicilio social",
            "ru": "Адрес юридического лица",
            "pt": "Morada da sede social",
            "it": "Indirizzo della sede legale",
            "hu": "Székhely címe",
        },
        options=None,
    ),
    "legal_representative_name": CatalogFieldPreset(
        key="legal_representative_name",
        field_type="text",
        labels={
            "fr": "Nom du gérant / représentant légal",
            "en": "Manager / legal representative name",
            "es": "Nombre del administrador / representante legal",
            "ru": "Имя директора / законного представителя",
            "pt": "Nome do gerente / representante legal",
            "it": "Nome dell'amministratore / rappresentante legale",
            "hu": "Ügyvezető / törvényes képviselő neve",
        },
        options=None,
    ),
    "partners_count": CatalogFieldPreset(
        key="partners_count",
        field_type="number",
        labels={
            "fr": "Nombre d'associés",
            "en": "Number of partners",
            "es": "Número de socios",
            "ru": "Количество участников",
            "pt": "Número de sócios",
            "it": "Numero di soci",
            "hu": "Tulajdonostársak száma",
        },
        options=None,
    ),
    "housing_address": CatalogFieldPreset(
        key="housing_address",
        field_type="address",
        labels={
            "fr": "Adresse du logement",
            "en": "Housing address",
            "es": "Dirección de la vivienda",
            "ru": "Адрес жилья",
            "pt": "Morada da habitação",
            "it": "Indirizzo dell'alloggio",
            "hu": "Lakás címe",
        },
        options=None,
    ),
    "housing_status": CatalogFieldPreset(
        key="housing_status",
        field_type="select",
        labels={
            "fr": "Statut du logement",
            "en": "Housing status",
            "es": "Situación de la vivienda",
            "ru": "Статус жилья",
            "pt": "Estatuto da habitação",
            "it": "Stato dell'alloggio",
            "hu": "Lakhatási státusz",
        },
        options={
            "fr": ["Propriétaire", "Locataire", "Hébergé", "En recherche", "Hôtel / temporaire"],
            "en": ["Owner", "Tenant", "Hosted", "Searching", "Hotel / temporary"],
            "es": ["Propietario", "Inquilino", "Alojado", "En búsqueda", "Hotel / temporal"],
            "ru": ["Собственник", "Арендатор", "Проживающий", "В поиске", "Отель / временное"],
            "pt": ["Proprietário", "Arrendatário", "Alojado", "Em procura", "Hotel / temporário"],
            "it": ["Proprietario", "Inquilino", "Ospitato", "In cerca", "Hotel / temporaneo"],
            "hu": [
                "Tulajdonos",
                "Bérlő",
                "Szívességi lakáshasználó",
                "Keresés alatt",
                "Hotel / ideiglenes",
            ],
        },
    ),
    "property_type": CatalogFieldPreset(
        key="property_type",
        field_type="select",
        labels={
            "fr": "Type de bien",
            "en": "Property type",
            "es": "Tipo de inmueble",
            "ru": "Тип недвижимости",
            "pt": "Tipo de imóvel",
            "it": "Tipo di immobile",
            "hu": "Ingatlan típusa",
        },
        options={
            "fr": ["Appartement", "Maison", "Studio", "Colocation", "Autre"],
            "en": ["Apartment", "House", "Studio", "Shared housing", "Other"],
            "es": ["Apartamento", "Casa", "Estudio", "Piso compartido", "Otro"],
            "ru": ["Квартира", "Дом", "Студия", "Совместная аренда", "Другое"],
            "pt": ["Apartamento", "Moradia", "Estúdio", "Quarto partilhado", "Outro"],
            "it": ["Appartamento", "Casa", "Monolocale", "Coabitazione", "Altro"],
            "hu": ["Lakás", "Ház", "Garzon", "Lakótársakkal", "Egyéb"],
        },
    ),
    "move_in_date": CatalogFieldPreset(
        key="move_in_date",
        field_type="date",
        labels={
            "fr": "Date d'emménagement souhaitée",
            "en": "Desired move-in date",
            "es": "Fecha deseada de mudanza",
            "ru": "Желаемая дата заселения",
            "pt": "Data de mudança pretendida",
            "it": "Data di trasloco desiderata",
            "hu": "Kívánt beköltözési dátum",
        },
        options=None,
    ),
    "tax_residence_country": CatalogFieldPreset(
        key="tax_residence_country",
        field_type="country",
        labels={
            "fr": "Pays de résidence fiscale",
            "en": "Country of tax residence",
            "es": "País de residencia fiscal",
            "ru": "Страна налогового резидентства",
            "pt": "País de residência fiscal",
            "it": "Paese di residenza fiscale",
            "hu": "Adóügyi illetőség országa",
        },
        options=None,
    ),
    "tax_id": CatalogFieldPreset(
        key="tax_id",
        field_type="text",
        labels={
            "fr": "Numéro d'identification fiscale (NIF / TIN…)",
            "en": "Tax identification number (NIF / TIN…)",
            "es": "Número de identificación fiscal (NIF / TIN…)",
            "ru": "Идентификационный номер налогоплательщика (NIF / TIN…)",
            "pt": "Número de identificação fiscal (NIF / TIN…)",
            "it": "Codice di identificazione fiscale (NIF / TIN…)",
            "hu": "Adóazonosító szám (NIF / TIN…)",
        },
        options=None,
    ),
    "target_tax_regime": CatalogFieldPreset(
        key="target_tax_regime",
        field_type="text",
        labels={
            "fr": "Régime fiscal visé",
            "en": "Target tax regime",
            "es": "Régimen fiscal previsto",
            "ru": "Целевой налоговый режим",
            "pt": "Regime fiscal pretendido",
            "it": "Regime fiscale di riferimento",
            "hu": "Célzott adózási forma",
        },
        options=None,
    ),
    "origin_country_tax_filing": CatalogFieldPreset(
        key="origin_country_tax_filing",
        field_type="boolean",
        labels={
            "fr": "Assujetti à déclaration dans le pays d'origine",
            "en": "Subject to filing in country of origin",
            "es": "Obligado a declarar en el país de origen",
            "ru": "Обязанность декларирования в стране происхождения",
            "pt": "Sujeito a declaração no país de origem",
            "it": "Soggetto a dichiarazione nel paese d'origine",
            "hu": "Bevallásra kötelezett a származási országban",
        },
        options=None,
    ),
    "tax_support_required": CatalogFieldPreset(
        key="tax_support_required",
        field_type="boolean",
        labels={
            "fr": "Accompagnement fiscal requis",
            "en": "Tax support required",
            "es": "Asesoramiento fiscal requerido",
            "ru": "Требуется налоговое сопровождение",
            "pt": "Acompanhamento fiscal necessário",
            "it": "Assistenza fiscale richiesta",
            "hu": "Adóügyi támogatás szükséges",
        },
        options=None,
    ),
    "host_language_level": CatalogFieldPreset(
        key="host_language_level",
        field_type="select",
        labels={
            "fr": "Niveau de langue du pays d'accueil",
            "en": "Host country language level",
            "es": "Nivel de idioma del país de acogida",
            "ru": "Уровень языка принимающей страны",
            "pt": "Nível de idioma do país de acolhimento",
            "it": "Livello di lingua del paese di accoglienza",
            "hu": "A fogadó ország nyelvének szintje",
        },
        options={
            "fr": [
                "Débutant A1",
                "Élémentaire A2",
                "Intermédiaire B1",
                "Avancé B2",
                "Autonome C1",
                "Maîtrise C2",
            ],
            "en": [
                "Beginner A1",
                "Elementary A2",
                "Intermediate B1",
                "Upper intermediate B2",
                "Advanced C1",
                "Proficient C2",
            ],
            "es": [
                "Principiante A1",
                "Elemental A2",
                "Intermedio B1",
                "Intermedio alto B2",
                "Avanzado C1",
                "Dominio C2",
            ],
            "ru": [
                "Начальный A1",
                "Элементарный A2",
                "Средний B1",
                "Продвинутый B2",
                "Свободный C1",
                "В совершенстве C2",
            ],
            "pt": [
                "Iniciante A1",
                "Elementar A2",
                "Intermédio B1",
                "Avançado B2",
                "Autónomo C1",
                "Domínio C2",
            ],
            "it": [
                "Principiante A1",
                "Elementare A2",
                "Intermedio B1",
                "Avanzato B2",
                "Autonomo C1",
                "Padronanza C2",
            ],
            "hu": [
                "Kezdő A1",
                "Alapszint A2",
                "Középszint B1",
                "Haladó B2",
                "Önálló C1",
                "Mesterfok C2",
            ],
        },
    ),
    "native_language": CatalogFieldPreset(
        key="native_language",
        field_type="text",
        labels={
            "fr": "Langue maternelle",
            "en": "Native language",
            "es": "Lengua materna",
            "ru": "Родной язык",
            "pt": "Língua materna",
            "it": "Lingua madre",
            "hu": "Anyanyelv",
        },
        options=None,
    ),
    "other_languages": CatalogFieldPreset(
        key="other_languages",
        field_type="text",
        labels={
            "fr": "Autres langues parlées",
            "en": "Other languages spoken",
            "es": "Otros idiomas hablados",
            "ru": "Другие языки",
            "pt": "Outras línguas faladas",
            "it": "Altre lingue parlate",
            "hu": "Egyéb beszélt nyelvek",
        },
        options=None,
    ),
    "interpreter_needed": CatalogFieldPreset(
        key="interpreter_needed",
        field_type="boolean",
        labels={
            "fr": "Besoin d'un traducteur / interprète",
            "en": "Translator / interpreter needed",
            "es": "Necesita traductor / intérprete",
            "ru": "Нужен переводчик / устный переводчик",
            "pt": "Necessidade de tradutor / intérprete",
            "it": "Necessità di un traduttore / interprete",
            "hu": "Fordítóra / tolmácsra van szükség",
        },
        options=None,
    ),
    "education_level": CatalogFieldPreset(
        key="education_level",
        field_type="text",
        labels={
            "fr": "Niveau d'études",
            "en": "Education level",
            "es": "Nivel de estudios",
            "ru": "Уровень образования",
            "pt": "Nível de escolaridade",
            "it": "Livello di istruzione",
            "hu": "Iskolai végzettség",
        },
        options=None,
    ),
    "last_institution": CatalogFieldPreset(
        key="last_institution",
        field_type="text",
        labels={
            "fr": "Établissement (dernier diplôme)",
            "en": "Institution (last degree)",
            "es": "Institución (último título)",
            "ru": "Учебное заведение (последний диплом)",
            "pt": "Instituição (último grau)",
            "it": "Istituto (ultimo titolo)",
            "hu": "Intézmény (utolsó diploma)",
        },
        options=None,
    ),
    "field_of_study": CatalogFieldPreset(
        key="field_of_study",
        field_type="text",
        labels={
            "fr": "Domaine d'études",
            "en": "Field of study",
            "es": "Ámbito de estudios",
            "ru": "Область обучения",
            "pt": "Área de estudos",
            "it": "Ambito di studio",
            "hu": "Tanulmányi terület",
        },
        options=None,
    ),
    "diploma_recognition": CatalogFieldPreset(
        key="diploma_recognition",
        field_type="boolean",
        labels={
            "fr": "Diplôme à faire reconnaître",
            "en": "Diploma to be recognized",
            "es": "Título a homologar",
            "ru": "Диплом для признания",
            "pt": "Diploma a reconhecer",
            "it": "Titolo da far riconoscere",
            "hu": "Elismertetendő diploma",
        },
        options=None,
    ),
    "children_school_preference": CatalogFieldPreset(
        key="children_school_preference",
        field_type="text",
        labels={
            "fr": "École souhaitée pour les enfants",
            "en": "Preferred school for children",
            "es": "Escuela deseada para los hijos",
            "ru": "Желаемая школа для детей",
            "pt": "Escola pretendida para os filhos",
            "it": "Scuola desiderata per i figli",
            "hu": "Kívánt iskola a gyermekeknek",
        },
        options=None,
    ),
    "target_school_start_date": CatalogFieldPreset(
        key="target_school_start_date",
        field_type="date",
        labels={
            "fr": "Date de rentrée visée",
            "en": "Target school start date",
            "es": "Fecha de inicio escolar prevista",
            "ru": "Целевая дата начала учёбы",
            "pt": "Data de início do ano letivo pretendida",
            "it": "Data di inizio scuola prevista",
            "hu": "Célzott iskolakezdési dátum",
        },
        options=None,
    ),
    "has_vehicle_to_import": CatalogFieldPreset(
        key="has_vehicle_to_import",
        field_type="boolean",
        labels={
            "fr": "Possède un véhicule à importer",
            "en": "Has a vehicle to import",
            "es": "Tiene un vehículo para importar",
            "ru": "Есть транспортное средство для ввоза",
            "pt": "Possui um veículo a importar",
            "it": "Possiede un veicolo da importare",
            "hu": "Importálandó járművel rendelkezik",
        },
        options=None,
    ),
    "vehicle_make_model": CatalogFieldPreset(
        key="vehicle_make_model",
        field_type="text",
        labels={
            "fr": "Marque / modèle du véhicule",
            "en": "Vehicle make / model",
            "es": "Marca / modelo del vehículo",
            "ru": "Марка / модель транспортного средства",
            "pt": "Marca / modelo do veículo",
            "it": "Marca / modello del veicolo",
            "hu": "Jármű márkája / modellje",
        },
        options=None,
    ),
    "vehicle_registration_number": CatalogFieldPreset(
        key="vehicle_registration_number",
        field_type="text",
        labels={
            "fr": "Numéro d'immatriculation (origine)",
            "en": "Registration number (origin)",
            "es": "Número de matrícula (origen)",
            "ru": "Регистрационный номер (исходный)",
            "pt": "Matrícula (origem)",
            "it": "Numero di targa (origine)",
            "hu": "Rendszám (származási ország)",
        },
        options=None,
    ),
    "driving_license_number": CatalogFieldPreset(
        key="driving_license_number",
        field_type="text",
        labels={
            "fr": "Numéro de permis de conduire",
            "en": "Driving licence number",
            "es": "Número de permiso de conducir",
            "ru": "Номер водительского удостоверения",
            "pt": "Número da carta de condução",
            "it": "Numero della patente di guida",
            "hu": "Vezetői engedély száma",
        },
        options=None,
    ),
    "license_to_exchange": CatalogFieldPreset(
        key="license_to_exchange",
        field_type="boolean",
        labels={
            "fr": "Permis à échanger / convertir",
            "en": "Licence to exchange / convert",
            "es": "Permiso a canjear / convertir",
            "ru": "Права для обмена / конвертации",
            "pt": "Carta a trocar / converter",
            "it": "Patente da convertire / sostituire",
            "hu": "Cserélendő / honosítandó engedély",
        },
        options=None,
    ),
    "license_country": CatalogFieldPreset(
        key="license_country",
        field_type="country",
        labels={
            "fr": "Pays d'émission du permis",
            "en": "Licence issuing country",
            "es": "País de emisión del permiso",
            "ru": "Страна выдачи прав",
            "pt": "País de emissão da carta",
            "it": "Paese di rilascio della patente",
            "hu": "Engedély kiállítási országa",
        },
        options=None,
    ),
    "secondary_email": CatalogFieldPreset(
        key="secondary_email",
        field_type="text",
        labels={
            "fr": "Email secondaire",
            "en": "Secondary email",
            "es": "Correo electrónico secundario",
            "ru": "Дополнительный email",
            "pt": "E-mail secundário",
            "it": "Email secondaria",
            "hu": "Másodlagos email",
        },
        options=None,
    ),
    "whatsapp": CatalogFieldPreset(
        key="whatsapp",
        field_type="text",
        labels={
            "fr": "WhatsApp",
            "en": "WhatsApp",
            "es": "WhatsApp",
            "ru": "WhatsApp",
            "pt": "WhatsApp",
            "it": "WhatsApp",
            "hu": "WhatsApp",
        },
        options=None,
    ),
    "preferred_language": CatalogFieldPreset(
        key="preferred_language",
        field_type="select",
        labels={
            "fr": "Langue de communication préférée",
            "en": "Preferred communication language",
            "es": "Idioma de comunicación preferido",
            "ru": "Предпочитаемый язык общения",
            "pt": "Idioma de comunicação preferido",
            "it": "Lingua di comunicazione preferita",
            "hu": "Preferált kommunikációs nyelv",
        },
        # Additive widening (data-prod field): Russian/German/Italian added
        # before the "Other" catch-all; the 5 original values are untouched.
        options={
            "fr": [
                "Français",
                "Anglais",
                "Espagnol",
                "Portugais",
                "Russe",
                "Allemand",
                "Italien",
                "Autre",
            ],
            "en": [
                "French",
                "English",
                "Spanish",
                "Portuguese",
                "Russian",
                "German",
                "Italian",
                "Other",
            ],
            "es": [
                "Francés",
                "Inglés",
                "Español",
                "Portugués",
                "Ruso",
                "Alemán",
                "Italiano",
                "Otro",
            ],
            "ru": [
                "Французский",
                "Английский",
                "Испанский",
                "Португальский",
                "Русский",
                "Немецкий",
                "Итальянский",
                "Другое",
            ],
            "pt": [
                "Francês",
                "Inglês",
                "Espanhol",
                "Português",
                "Russo",
                "Alemão",
                "Italiano",
                "Outro",
            ],
            "it": [
                "Francese",
                "Inglese",
                "Spagnolo",
                "Portoghese",
                "Russo",
                "Tedesco",
                "Italiano",
                "Altro",
            ],
            "hu": ["Francia", "Angol", "Spanyol", "Portugál", "Orosz", "Német", "Olasz", "Egyéb"],
        },
    ),
    "preferred_contact_channel": CatalogFieldPreset(
        key="preferred_contact_channel",
        field_type="select",
        labels={
            "fr": "Canal de contact préféré",
            "en": "Preferred contact channel",
            "es": "Canal de contacto preferido",
            "ru": "Предпочитаемый канал связи",
            "pt": "Canal de contacto preferido",
            "it": "Canale di contatto preferito",
            "hu": "Preferált kapcsolattartási csatorna",
        },
        options={
            "fr": ["Email", "WhatsApp", "SMS", "Téléphone", "Espace client"],
            "en": ["Email", "WhatsApp", "SMS", "Phone", "Client portal"],
            "es": ["Correo electrónico", "WhatsApp", "SMS", "Teléfono", "Portal del cliente"],
            "ru": ["Email", "WhatsApp", "SMS", "Телефон", "Кабинет клиента"],
            "pt": ["E-mail", "WhatsApp", "SMS", "Telefone", "Espaço do cliente"],
            "it": ["Email", "WhatsApp", "SMS", "Telefono", "Spazio cliente"],
            "hu": ["Email", "WhatsApp", "SMS", "Telefon", "Ügyfélportál"],
        },
    ),
    # === Sector packs (bloc packs sectoriels) — new presets ============================
    # --- real_estate_deal (secteur real_estate) ---------------------------------------
    "property_deal_type": CatalogFieldPreset(
        key="property_deal_type",
        field_type="select",
        labels={
            "fr": "Type de transaction",
            "en": "Deal type",
            "es": "Tipo de operación",
            "ru": "Тип сделки",
            "pt": "Tipo de transação",
            "it": "Tipo di transazione",
            "hu": "Ügylet típusa",
        },
        options={
            "fr": ["Vente", "Location", "Gestion"],
            "en": ["Sale", "Rental", "Management"],
            "es": ["Venta", "Alquiler", "Gestión"],
            "ru": ["Продажа", "Аренда", "Управление"],
            "pt": ["Venda", "Arrendamento", "Gestão"],
            "it": ["Vendita", "Locazione", "Gestione"],
            "hu": ["Eladás", "Bérlés", "Kezelés"],
        },
    ),
    "property_kind": CatalogFieldPreset(
        key="property_kind",
        field_type="select",
        labels={
            "fr": "Type de bien",
            "en": "Property type",
            "es": "Tipo de inmueble",
            "ru": "Тип объекта",
            "pt": "Tipo de imóvel",
            "it": "Tipo di immobile",
            "hu": "Ingatlan típusa",
        },
        options={
            "fr": ["Maison", "Appartement", "Terrain", "Local commercial", "Immeuble"],
            "en": ["House", "Apartment", "Land", "Commercial premises", "Building"],
            "es": ["Casa", "Apartamento", "Terreno", "Local comercial", "Edificio"],
            "ru": ["Дом", "Квартира", "Земельный участок", "Коммерческое помещение", "Здание"],
            "pt": ["Casa", "Apartamento", "Terreno", "Espaço comercial", "Prédio"],
            "it": ["Casa", "Appartamento", "Terreno", "Locale commerciale", "Edificio"],
            "hu": ["Ház", "Lakás", "Telek", "Üzlethelyiség", "Épület"],
        },
    ),
    "property_address": CatalogFieldPreset(
        key="property_address",
        field_type="address",
        labels={
            "fr": "Adresse du bien",
            "en": "Property address",
            "es": "Dirección del inmueble",
            "ru": "Адрес объекта",
            "pt": "Endereço do imóvel",
            "it": "Indirizzo dell'immobile",
            "hu": "Ingatlan címe",
        },
        options=None,
    ),
    "property_surface": CatalogFieldPreset(
        key="property_surface",
        field_type="number",
        labels={
            "fr": "Surface (m²)",
            "en": "Surface area (m²)",
            "es": "Superficie (m²)",
            "ru": "Площадь (м²)",
            "pt": "Área (m²)",
            "it": "Superficie (m²)",
            "hu": "Alapterület (m²)",
        },
        options=None,
    ),
    "property_rooms": CatalogFieldPreset(
        key="property_rooms",
        field_type="number",
        labels={
            "fr": "Nombre de pièces",
            "en": "Number of rooms",
            "es": "Número de habitaciones",
            "ru": "Количество комнат",
            "pt": "Número de divisões",
            "it": "Numero di locali",
            "hu": "Szobák száma",
        },
        options=None,
    ),
    "property_price": CatalogFieldPreset(
        key="property_price",
        field_type="number",
        labels={
            "fr": "Prix du bien",
            "en": "Property price",
            "es": "Precio del inmueble",
            "ru": "Цена объекта",
            "pt": "Preço do imóvel",
            "it": "Prezzo dell'immobile",
            "hu": "Ingatlan ára",
        },
        options=None,
    ),
    "mandate_type": CatalogFieldPreset(
        key="mandate_type",
        field_type="select",
        labels={
            "fr": "Type de mandat",
            "en": "Mandate type",
            "es": "Tipo de mandato",
            "ru": "Тип поручения",
            "pt": "Tipo de mandato",
            "it": "Tipo di mandato",
            "hu": "Megbízás típusa",
        },
        options={
            "fr": ["Simple", "Exclusif", "Semi-exclusif"],
            "en": ["Open", "Exclusive", "Semi-exclusive"],
            "es": ["Simple", "Exclusivo", "Semiexclusivo"],
            "ru": ["Простой", "Эксклюзивный", "Полуэксклюзивный"],
            "pt": ["Simples", "Exclusivo", "Semiexclusivo"],
            "it": ["Semplice", "Esclusivo", "Semi-esclusivo"],
            "hu": ["Egyszerű", "Kizárólagos", "Fél-kizárólagos"],
        },
    ),
    "mandate_number": CatalogFieldPreset(
        key="mandate_number",
        field_type="text",
        labels={
            "fr": "Numéro de mandat",
            "en": "Mandate number",
            "es": "Número de mandato",
            "ru": "Номер поручения",
            "pt": "Número do mandato",
            "it": "Numero di mandato",
            "hu": "Megbízás száma",
        },
        options=None,
    ),
    "transaction_stage": CatalogFieldPreset(
        key="transaction_stage",
        field_type="select",
        labels={
            "fr": "Étape de la transaction",
            "en": "Transaction stage",
            "es": "Etapa de la operación",
            "ru": "Этап сделки",
            "pt": "Etapa da transação",
            "it": "Fase della transazione",
            "hu": "Ügylet szakasza",
        },
        options={
            "fr": [
                "Estimation",
                "Mandat",
                "Visites",
                "Offre",
                "Signature préliminaire",
                "Acte final",
            ],
            "en": [
                "Valuation",
                "Mandate",
                "Viewings",
                "Offer",
                "Preliminary agreement",
                "Final deed",
            ],
            "es": [
                "Valoración",
                "Mandato",
                "Visitas",
                "Oferta",
                "Contrato preliminar",
                "Escritura final",
            ],
            "ru": [
                "Оценка",
                "Поручение",
                "Просмотры",
                "Предложение",
                "Предварительный договор",
                "Окончательный акт",
            ],
            "pt": [
                "Avaliação",
                "Mandato",
                "Visitas",
                "Oferta",
                "Contrato-promessa",
                "Escritura final",
            ],
            "it": ["Valutazione", "Mandato", "Visite", "Offerta", "Compromesso", "Atto definitivo"],
            "hu": [
                "Értékbecslés",
                "Megbízás",
                "Megtekintések",
                "Ajánlat",
                "Előszerződés",
                "Végleges adásvétel",
            ],
        },
    ),
    "energy_performance": CatalogFieldPreset(
        key="energy_performance",
        field_type="text",
        labels={
            "fr": "Performance énergétique (DPE)",
            "en": "Energy performance rating",
            "es": "Certificado energético",
            "ru": "Энергоэффективность",
            "pt": "Certificado energético",
            "it": "Prestazione energetica (APE)",
            "hu": "Energetikai besorolás",
        },
        options=None,
    ),
    "expected_signing_date": CatalogFieldPreset(
        key="expected_signing_date",
        field_type="date",
        labels={
            "fr": "Date de signature prévue",
            "en": "Expected signing date",
            "es": "Fecha prevista de firma",
            "ru": "Планируемая дата подписания",
            "pt": "Data prevista de assinatura",
            "it": "Data prevista di firma",
            "hu": "Várható aláírás dátuma",
        },
        options=None,
    ),
    "agency_fee_percent": CatalogFieldPreset(
        key="agency_fee_percent",
        field_type="number",
        labels={
            "fr": "Honoraires d'agence (%)",
            "en": "Agency fee (%)",
            "es": "Honorarios de agencia (%)",
            "ru": "Комиссия агентства (%)",
            "pt": "Comissão da agência (%)",
            "it": "Commissione d'agenzia (%)",
            "hu": "Ügynökségi díj (%)",
        },
        options=None,
    ),
    # --- wealth_review (secteur wealth) -----------------------------------------------
    "risk_profile": CatalogFieldPreset(
        key="risk_profile",
        field_type="select",
        labels={
            "fr": "Profil de risque",
            "en": "Risk profile",
            "es": "Perfil de riesgo",
            "ru": "Профиль риска",
            "pt": "Perfil de risco",
            "it": "Profilo di rischio",
            "hu": "Kockázati profil",
        },
        options={
            "fr": ["Prudent", "Équilibré", "Dynamique", "Offensif"],
            "en": ["Conservative", "Balanced", "Dynamic", "Aggressive"],
            "es": ["Conservador", "Equilibrado", "Dinámico", "Agresivo"],
            "ru": ["Консервативный", "Сбалансированный", "Динамичный", "Агрессивный"],
            "pt": ["Conservador", "Equilibrado", "Dinâmico", "Agressivo"],
            "it": ["Prudente", "Bilanciato", "Dinamico", "Aggressivo"],
            "hu": ["Óvatos", "Kiegyensúlyozott", "Dinamikus", "Agresszív"],
        },
    ),
    "wealth_objective": CatalogFieldPreset(
        key="wealth_objective",
        field_type="select",
        labels={
            "fr": "Objectif patrimonial",
            "en": "Wealth objective",
            "es": "Objetivo patrimonial",
            "ru": "Цель управления капиталом",
            "pt": "Objetivo patrimonial",
            "it": "Obiettivo patrimoniale",
            "hu": "Vagyoni cél",
        },
        options={
            "fr": ["Retraite", "Transmission", "Optimisation fiscale", "Revenus", "Valorisation"],
            "en": ["Retirement", "Estate transfer", "Tax optimization", "Income", "Capital growth"],
            "es": ["Jubilación", "Transmisión", "Optimización fiscal", "Ingresos", "Valorización"],
            "ru": [
                "Пенсия",
                "Передача наследства",
                "Налоговая оптимизация",
                "Доход",
                "Прирост капитала",
            ],
            "pt": ["Reforma", "Transmissão", "Otimização fiscal", "Rendimentos", "Valorização"],
            "it": [
                "Pensione",
                "Trasmissione",
                "Ottimizzazione fiscale",
                "Reddito",
                "Rivalutazione",
            ],
            "hu": ["Nyugdíj", "Vagyonátadás", "Adóoptimalizálás", "Jövedelem", "Értéknövelés"],
        },
    ),
    "investment_horizon": CatalogFieldPreset(
        key="investment_horizon",
        field_type="select",
        labels={
            "fr": "Horizon d'investissement",
            "en": "Investment horizon",
            "es": "Horizonte de inversión",
            "ru": "Инвестиционный горизонт",
            "pt": "Horizonte de investimento",
            "it": "Orizzonte d'investimento",
            "hu": "Befektetési időtáv",
        },
        options={
            "fr": ["Court terme", "Moyen terme", "Long terme"],
            "en": ["Short term", "Medium term", "Long term"],
            "es": ["Corto plazo", "Medio plazo", "Largo plazo"],
            "ru": ["Краткосрочный", "Среднесрочный", "Долгосрочный"],
            "pt": ["Curto prazo", "Médio prazo", "Longo prazo"],
            "it": ["Breve termine", "Medio termine", "Lungo termine"],
            "hu": ["Rövid táv", "Közép táv", "Hosszú táv"],
        },
    ),
    "estimated_wealth": CatalogFieldPreset(
        key="estimated_wealth",
        field_type="number",
        labels={
            "fr": "Patrimoine estimé",
            "en": "Estimated wealth",
            "es": "Patrimonio estimado",
            "ru": "Оценочный капитал",
            "pt": "Património estimado",
            "it": "Patrimonio stimato",
            "hu": "Becsült vagyon",
        },
        options=None,
    ),
    "savings_capacity": CatalogFieldPreset(
        key="savings_capacity",
        field_type="number",
        labels={
            "fr": "Capacité d'épargne",
            "en": "Savings capacity",
            "es": "Capacidad de ahorro",
            "ru": "Способность к сбережению",
            "pt": "Capacidade de poupança",
            "it": "Capacità di risparmio",
            "hu": "Megtakarítási képesség",
        },
        options=None,
    ),
    "funds_origin": CatalogFieldPreset(
        key="funds_origin",
        field_type="select",
        labels={
            "fr": "Origine des fonds",
            "en": "Source of funds",
            "es": "Origen de los fondos",
            "ru": "Источник средств",
            "pt": "Origem dos fundos",
            "it": "Origine dei fondi",
            "hu": "Pénzeszközök eredete",
        },
        options={
            "fr": ["Épargne", "Cession", "Héritage", "Donation", "Activité professionnelle"],
            "en": ["Savings", "Asset sale", "Inheritance", "Gift", "Professional activity"],
            "es": ["Ahorro", "Venta de activos", "Herencia", "Donación", "Actividad profesional"],
            "ru": [
                "Сбережения",
                "Продажа активов",
                "Наследство",
                "Дарение",
                "Профессиональная деятельность",
            ],
            "pt": ["Poupança", "Alienação", "Herança", "Doação", "Atividade profissional"],
            "it": ["Risparmio", "Cessione", "Eredità", "Donazione", "Attività professionale"],
            "hu": [
                "Megtakarítás",
                "Eszközértékesítés",
                "Örökség",
                "Ajándékozás",
                "Szakmai tevékenység",
            ],
        },
    ),
    "held_products": CatalogFieldPreset(
        key="held_products",
        field_type="text",
        labels={
            "fr": "Produits détenus",
            "en": "Products held",
            "es": "Productos en cartera",
            "ru": "Имеющиеся продукты",
            "pt": "Produtos detidos",
            "it": "Prodotti detenuti",
            "hu": "Meglévő termékek",
        },
        options=None,
    ),
    "esg_preference": CatalogFieldPreset(
        key="esg_preference",
        field_type="select",
        labels={
            "fr": "Préférence ESG",
            "en": "ESG preference",
            "es": "Preferencia ESG",
            "ru": "ESG-предпочтение",
            "pt": "Preferência ESG",
            "it": "Preferenza ESG",
            "hu": "ESG-preferencia",
        },
        options={
            "fr": ["Oui", "Non", "Partiel"],
            "en": ["Yes", "No", "Partial"],
            "es": ["Sí", "No", "Parcial"],
            "ru": ["Да", "Нет", "Частично"],
            "pt": ["Sim", "Não", "Parcial"],
            "it": ["Sì", "No", "Parziale"],
            "hu": ["Igen", "Nem", "Részleges"],
        },
    ),
    # --- consulting_mission (secteur consulting) --------------------------------------
    "mission_type": CatalogFieldPreset(
        key="mission_type",
        field_type="select",
        labels={
            "fr": "Type de mission",
            "en": "Mission type",
            "es": "Tipo de misión",
            "ru": "Тип задания",
            "pt": "Tipo de missão",
            "it": "Tipo di incarico",
            "hu": "Megbízás típusa",
        },
        options={
            "fr": ["Diagnostic", "Assistance projet", "Accompagnement", "Audit", "Formation"],
            "en": ["Assessment", "Project assistance", "Support", "Audit", "Training"],
            "es": [
                "Diagnóstico",
                "Asistencia de proyecto",
                "Acompañamiento",
                "Auditoría",
                "Formación",
            ],
            "ru": [
                "Диагностика",
                "Поддержка проекта",
                "Сопровождение",
                "Аудит",
                "Обучение",
            ],
            "pt": [
                "Diagnóstico",
                "Assistência de projeto",
                "Acompanhamento",
                "Auditoria",
                "Formação",
            ],
            "it": [
                "Diagnosi",
                "Assistenza di progetto",
                "Accompagnamento",
                "Audit",
                "Formazione",
            ],
            "hu": ["Felmérés", "Projekttámogatás", "Támogatás", "Audit", "Képzés"],
        },
    ),
    "billing_mode": CatalogFieldPreset(
        key="billing_mode",
        field_type="select",
        labels={
            "fr": "Mode de facturation",
            "en": "Billing mode",
            "es": "Modo de facturación",
            "ru": "Способ выставления счетов",
            "pt": "Modo de faturação",
            "it": "Modalità di fatturazione",
            "hu": "Számlázási mód",
        },
        options={
            "fr": ["Forfait", "Temps passé", "Abonnement"],
            "en": ["Fixed price", "Time & materials", "Subscription"],
            "es": ["Precio fijo", "Por tiempo", "Suscripción"],
            "ru": ["Фиксированная цена", "Повременная оплата", "Подписка"],
            "pt": ["Preço fixo", "Por tempo", "Subscrição"],
            "it": ["Forfait", "A consumo", "Abbonamento"],
            "hu": ["Átalánydíj", "Ráfordítás alapú", "Előfizetés"],
        },
    ),
    "daily_rate": CatalogFieldPreset(
        key="daily_rate",
        field_type="number",
        labels={
            "fr": "Taux journalier moyen (TJM)",
            "en": "Average daily rate",
            "es": "Tarifa diaria media",
            "ru": "Средняя дневная ставка",
            "pt": "Tarifa diária média",
            "it": "Tariffa giornaliera media",
            "hu": "Átlagos napidíj",
        },
        options=None,
    ),
    "sold_budget": CatalogFieldPreset(
        key="sold_budget",
        field_type="number",
        labels={
            "fr": "Budget vendu",
            "en": "Sold budget",
            "es": "Presupuesto vendido",
            "ru": "Проданный бюджет",
            "pt": "Orçamento vendido",
            "it": "Budget venduto",
            "hu": "Eladott költségvetés",
        },
        options=None,
    ),
    "sold_days": CatalogFieldPreset(
        key="sold_days",
        field_type="number",
        labels={
            "fr": "Jours vendus",
            "en": "Sold days",
            "es": "Días vendidos",
            "ru": "Проданные дни",
            "pt": "Dias vendidos",
            "it": "Giornate vendute",
            "hu": "Eladott napok",
        },
        options=None,
    ),
    "completion_rate": CatalogFieldPreset(
        key="completion_rate",
        field_type="number",
        labels={
            "fr": "Taux d'avancement (%)",
            "en": "Completion rate (%)",
            "es": "Porcentaje de avance (%)",
            "ru": "Процент выполнения (%)",
            "pt": "Taxa de conclusão (%)",
            "it": "Percentuale di avanzamento (%)",
            "hu": "Készültségi fok (%)",
        },
        options=None,
    ),
    "consumed_days": CatalogFieldPreset(
        key="consumed_days",
        field_type="number",
        labels={
            "fr": "Jours consommés",
            "en": "Days consumed",
            "es": "Días consumidos",
            "ru": "Использованные дни",
            "pt": "Dias consumidos",
            "it": "Giornate consumate",
            "hu": "Felhasznált napok",
        },
        options=None,
    ),
    "expected_deliverables": CatalogFieldPreset(
        key="expected_deliverables",
        field_type="text",
        labels={
            "fr": "Livrables attendus",
            "en": "Expected deliverables",
            "es": "Entregables esperados",
            "ru": "Ожидаемые результаты",
            "pt": "Entregáveis esperados",
            "it": "Deliverable attesi",
            "hu": "Várt eredmények",
        },
        options=None,
    ),
    "steering_committee_freq": CatalogFieldPreset(
        key="steering_committee_freq",
        field_type="select",
        labels={
            "fr": "Fréquence du comité de pilotage",
            "en": "Steering committee frequency",
            "es": "Frecuencia del comité de dirección",
            "ru": "Частота руководящего комитета",
            "pt": "Frequência do comité de pilotagem",
            "it": "Frequenza del comitato direttivo",
            "hu": "Irányítóbizottság gyakorisága",
        },
        # "Bi-mensuel" = TWICE A MONTH / every two weeks (intent confirmed).
        options={
            "fr": ["Hebdomadaire", "Bi-mensuel", "Mensuel", "Ponctuel"],
            "en": ["Weekly", "Bi-weekly", "Monthly", "Ad hoc"],
            "es": ["Semanal", "Quincenal", "Mensual", "Puntual"],
            "ru": ["Еженедельно", "Раз в две недели", "Ежемесячно", "По необходимости"],
            "pt": ["Semanal", "Quinzenal", "Mensal", "Pontual"],
            "it": ["Settimanale", "Bisettimanale", "Mensile", "Occasionale"],
            "hu": ["Heti", "Kéthetente", "Havi", "Eseti"],
        },
    ),
}


def field_kind(key: str) -> str:
    """base_field for the native civil columns, custom_field otherwise."""
    return "base_field" if key in COLLECTABLE_BASE_FIELDS else "custom_field"
